openapi: 3.0.2
info:
  title: advanced-sns API
  version: 1.0.0
paths:
  /auth:
    $ref: './paths/auth.yaml'
  /account:
    $ref: './paths/account.yaml'
  /account/icon_image:
    $ref: './paths/account/icon_image.yaml'
  /account/profile:
    $ref: './paths/account/profile.yaml'
  /posts:
    $ref: './paths/posts/index.yaml'
  '/posts/{id}':
    $ref: './paths/posts/_id.yaml'
  /rooms:
    $ref: './paths/rooms/index.yaml'
  '/rooms/{id}':
    $ref: './paths/rooms/_id.yaml'
  '/rooms/{id}/read':
    $ref: './paths/rooms/read.yaml'
  /messages:
    $ref: './paths/messages/index.yaml'
  /messages/via_post:
    $ref: './paths/messages/via_post.yaml'
  /timeline/by_each_person:
    $ref: './paths/timeline/by_each_person.yaml'
  /friend_requests:
    $ref: './paths/friend_requests/index.yaml'
  /friend_requests/receiving:
    $ref: './paths/friend_requests/receiving.yaml'
  /friend_requests/status:
    $ref: './paths/friend_requests/status.yaml'
  /friends:
    $ref: './paths/friends/index.yaml'
  /post_seen_logs:
    $ref: './paths/post_seen_log/index.yaml'
  /friendships:
    $ref: './paths/friendships/index.yaml'
  /users:
    $ref: './paths/users/index.yaml'
  '/users/{id}':
    $ref: './paths/users/_id.yaml'
  /message_reactions:
    $ref: './paths/message_reactions/index.yaml'
  '/message_reactions/{id}':
    $ref: './paths/message_reactions/_id.yaml'
 
 
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: このAPIはBearerトークンを使って認証します

  schemas:
    EntityMessage:
      $ref: './components/schemas/entity/message.yaml'
    EntityAccount:
      $ref: './components/schemas/entity/account.yaml'
    EntityPost:
      $ref: './components/schemas/entity/post.yaml'
    EntityUser:
      $ref: './components/schemas/entity/user.yaml'
    EntityRoom:
      $ref: './components/schemas/entity/room.yaml'
    EntityRoomUser:
      $ref: './components/schemas/entity/room_user.yaml'
    EntityFriendRequest:
      $ref: './components/schemas/entity/friend_request.yaml'
    EntityFriendship:
      $ref: './components/schemas/entity/frinedship.yaml'
    EntityMessageReaction:
      $ref: './components/schemas/entity/message_reaction.yaml'
    EntityPostSeenLog:
      $ref: './components/schemas/entity/post_seen_log.yaml'
    EntityPostViewable:
      $ref: './components/schemas/entity/post_viewable.yaml'
    EntityTimeline:
      $ref: './components/schemas/entity/timeline.yaml'
    EnumFriendRequestStatus:
      $ref: './components/schemas/enum/friend_request_status.yaml'

  responses:
    # General Responses
    ResponseSuccess:
      $ref: './components/responses/success.yaml'
    ResponseBadRequest:
      $ref: './components/responses/bad_request.yaml'

    # Resource Responses
    ResponseNullableAccount:
      $ref: './components/responses/nullable_account.yaml'
    ResponseAccount:
      $ref: './components/responses/account.yaml'
    ResponseRoomList:
      $ref: './components/responses/room_list.yaml'
    ResponseRoom:
      $ref: './components/responses/room.yaml'
    ResponseSignIn:
      $ref: './components/responses/sign_in.yaml'
    ResponsePost:
      $ref: './components/responses/post.yaml'
    ResponsePostList:
      $ref: './components/responses/post_list.yaml'
    ResponseMedia:
      $ref: './components/responses/media.yaml'
    ResponseMessageList:
      $ref: './components/responses/message_list.yaml'
    ResponseMessage:
      $ref: './components/responses/message.yaml'
    ResponseTimelineList:
      $ref: './components/responses/timeline_list.yaml'
    ResponseFriendRequestList:
      $ref: './components/responses/friend_request_list.yaml'
    ResponseFriendList:
      $ref: './components/responses/friend_list.yaml'
    ResponsePostSeenLogList:
      $ref: './components/responses/post_seen_log_list.yaml'
    ResponseFriendshipList:
      $ref: './components/responses/friendship_list.yaml'
    ResponseUserList:
      $ref: './components/responses/user_list.yaml'
    ResponseUser:
      $ref: './components/responses/user.yaml'
    ResponseMessageReaction:
      $ref: './components/responses/message_reaction.yaml'
